sqoop job --exec order_items_postgres
sqoop job --exec products_postgres
sqoop job --exec product_categories_postgres
sqoop job --exec inventories_postgres
sqoop job --exec customers_mysql
sqoop job --exec contacts_mysql
sqoop job --exec orders_mysql
sqoop job --exec employees_mysql
sqoop job --exec warehouses_oracle
sqoop job --exec locations_oracle
